title: Configuring Kubernetes kubectl in an Actions Workflow
tagline: A brand new course on Learning Lab
description: >-
  This course guides the student through a step-by-step process to configure the
  Kubernetes kubectl command in a GitHub Actions Workflow.
template:
  repo: configuring-kubernetes-kubectl-in-an-actions-workflow-template
  name: configuring-kubernetes-kubectl-in-an-actions-workflow
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
